import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/src/components/Header";
import "@/src/styles/globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Next Routing",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode
};

export default function RootLayout({ children }: Props) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Header />
            {children}
        </body>
        </html>
    );
}